export const CORPORATE_IMMIGRATION_LINKS = [
  { label: "Business Visitor Visa", href: "#" },
  { label: "Global Talent Visa", href: "#" },
  { label: "Graduate Trainee Visa", href: "#" },
  { label: "Graduate Visa", href: "#" },
  { label: "High Potential Individual (HPI) Visa", href: "#" },
  { label: "Innovator Visa", href: "#" },
  { label: "Overseas Business Representative Visa", href: "#" },
  { label: "Secondment Worker Visa", href: "#" },
  { label: "Senior or Specialist Worker Visa", href: "#" },
  { label: "Service Supplier Visa", href: "#" },
  { label: "Skilled Worker Visa", href: "#" },
  { label: "Sponsorship Licence", href: "#" },

  { label: "Start-up Visa", href: "#" },
  { label: "Temporary Worker Visa", href: "#" },
  { label: "Tier 1 Entrepreneur Visa", href: "#" },
  { label: "Tier 1 Exceptional Talent", href: "#" },
  { label: "Tier 1 General Visa", href: "#" },
  { label: "Tier 2 General Visa", href: "#" },
  { label: "Tier 2 Intra Company Transfer Visa", href: "#" },
  { label: "Tier 1 Investor Visa", href: "#" },
  { label: "Tier 2 Sportsperson", href: "#" },
  { label: "UK Expansion Worker Visa", href: "#" },
];